### ISSUE TITLE
How to download the dataset？

### ISSUE THREAD

**Issue by freshwindy** [Moon-sung-woo/MIST_Tacotron#1]
Hi,this is very helpful.Thanks for your share.But how to download the dataset?I click on the multi-speaker link and it doesn't take me to the dataset page, and where can I download the single-speaker dataset?

**Comment by Moon-sung-woo** [comment]
Hi @freshwindy 
https://github.com/emotiontts/emotiontts_open_db/tree/master/Dataset/SpeechCorpus
This is multi-speaker dataset link

If you want to use a multi-emotion dataset, visit http://aicompanion.or.kr/kor/main/#
Join this web and login
then go to '기술공유' -> 데이터 공유 -> '감정 음성합성 데이터셋'
You can download data

**Comment by freshwindy** [comment]
> Hi @freshwindy https://github.com/emotiontts/emotiontts_open_db/tree/master/Dataset/SpeechCorpus This is multi-speaker dataset link
> 
> If you want to use a multi-emotion dataset, visit http://aicompanion.or.kr/kor/main/# Join this web and login then go to '기술공유' -> 데이터 공유 -> '감정 음성합성 데이터셋' You can download data

Thanks for your answer.But I still can't jump to the second link when I click it. Here is the page after I click it. In addition, whether the above two links contain a single speaker dataset？
![image](https://user-images.githubusercontent.com/100998024/204032372-eba0aad5-bf21-4895-ae8b-9962c6730281.png)

**Comment by Moon-sung-woo** [comment]
Um... In korea we can enter this site.
I think you'd better use VPN.

Two link contain single speaker dateset.
But in my paper, i used only single speaker in first link.

**Comment by freshwindy** [comment]
Hi,I use vpn that node is located in Korea,but i can't jump to.I don't know whether there are other sharing methods for this dataset, such as Google Cloud Disk.

**Comment by Moon-sung-woo** [comment]
I understand that there is no other way to do it because of the license.

**Comment by Moon-sung-woo** [comment]
Close due to inactivity.
